# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshmanager', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
