# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sshmanager', '0003_token_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
