# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshmanager', '0004_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
