# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshmanager', '0005_token_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='token',
            name='obs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
